server:
  port: 5000
spring:
  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME:localhost}:${RDS_PORT:3306}/${RDS_DB_NAME:shop}?useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw&autoReconnect=true&characterEncoding=UTF-8&useUnicode=yes
    username: ${RDS_USERNAME:root}
    password: ${RDS_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  flyway:
    baseline-on-migrate: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SECRET_SHOP_EMAIL_USERNAME}
    password: ${SECRET_SHOP_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp
file:
  product: C:\Users\Piotr\OneDrive\Pulpit\images
amazonProperties:
  endpointUrl: https://s3.eu-central-1.amazonaws.com
  accessKey: ${SECRET_SHOP_S3_KEY:localkey}
  secretKey: ${SECRET_SHOP_S3_SECRET:localsecret}
  bucketName: shop-krh-images
#    enabled: false
